/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export { }
declare global {

}

declare interface Reflect {
  get(target: object, propertyKey: PropertyKey, receiver?: any): void
}

declare function Reflect.get(target: object, propertyKey: PropertyKey, receiver ?: any): void
